#!/bin/bash

# Start celery if there is a RabbitMQ cart
if [ -n "$OPENSHIFT_RABBITMQ_URI" ]; then
   cd $OPENSHIFT_REPO_DIR/wsgi/

   PID_FILE=$OPENSHIFT_DATA_DIR/celery-worker.pid

   celery worker --app=openshift.celery:app --detach --pidfile=$PID_FILE |& /usr/bin/logshifter -tag celery
   echo Started Celery Worker
fi
